name: Output information
on:
  issues:
    types: [opened]
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output event details
        run: |
          echo "${{ toJSON(github.repository) }}"
          echo "${{ toJSON(github.event_name) }}"
          echo "${{ toJSON(github.event_path) }}"